const ingredientsList = {
  Alcohol: ['Vodka', 'Gin', 'Rum', 'Tequila', 'Whiskey', 'Brandy'],
  Mixers: [
    'Tonic Water',
    'Club Soda',
    'Ginger Beer',
    'Cola',
    'Lemon-Lime Soda',
    'Ginger Ale',
    'Orange Juice',
    'Cranberry Juice',
    'Pineapple Juice',
    'Grapefruit Juice',
    'Tomato Juice',
    'Coconut Water',
  ],
  Sweeteners: [
    'Simple Syrup',
    'Honey Syrup',
    'Agave Syrup',
    'Maple Syrup',
    'Grenadine',
    'Orgeat Syrup',
    'Cinnamon Syrup',
    'Vanilla Syrup',
    'Coconut Cream',
  ],
  Citrus: ['Lemon', 'Lime', 'Orange', 'Grapefruit', 'Pineapple'],
  Bitters: [
    'Angostura Bitters',
    'Orange Bitters',
    'Grapefruit Bitters',
    'Cardamom Bitters',
    'Chocolate Bitters',
    'Cherry Bitters',
    'Celery Bitters',
    'Mole Bitters',
  ],
  Garnishes: [
    'Lemon Twist',
    'Lime Wedge',
    'Orange Slice',
    'Grapefruit Twist',
    'Pineapple Wedge',
    'Cherry',
    'Olives',
    'Mint Sprig',
    'Basil Leaf',
    'Cucumber Slice',
    'Celery Stalk',
    'Cinnamon Stick',
  ],
  Other: ['Ice', 'Water'],
};

export default ingredientsList;
