const ingredientsList = {
  Alcohol: [
    'Vodka',
    'Gin',
    'Rum',
    'Tequila',
    'Whiskey',
    'Brandy',
    'Cognac',
    'Scotch',
    'Bourbon',
    'Rye Whiskey',
    'Irish Whiskey',
    'Triple Sec',
    'Cointreau',
    'Campari',
    'Amaretto',
    'Baileys Irish Cream',
    'Kahlua',
    'Grand Marnier',
    'Frangelico',
    'Chambord',
    'Drambuie',
    'Midori',
    'Malibu Rum',
    'Peach Schnapps',
    'Creme de Menthe',
    'Creme de Cassis',
    'Galliano',
    'Sambuca',
    'Absinthe',
    'Pisco',
    'Aperol',
  ],
  Mixers: [
    'Tonic Water',
    'Club Soda',
    'Ginger Beer',
    'Cola',
    'Lemon-Lime Soda',
    'Ginger Ale',
    'Orange Juice',
    'Cranberry Juice',
    'Pineapple Juice',
    'Grapefruit Juice',
    'Tomato Juice',
    'Coconut Water',
    'Sprite',
    'Coca-Cola',
    'Lemonade',
    'Iced Tea',
    'Energy Drink',
    'Bitter Lemon',
    'Fruit Punch',
  ],
  Sweeteners: [
    'Simple Syrup',
    'Honey Syrup',
    'Agave Syrup',
    'Maple Syrup',
    'Grenadine',
    'Orgeat Syrup',
    'Cinnamon Syrup',
    'Vanilla Syrup',
    'Coconut Cream',
    'Sugar Cubes',
    'Brown Sugar',
    'Powdered Sugar',
    'Stevia',
    'Splenda',
    'Equal',
  ],
  Citrus: [
    'Lemon',
    'Lime',
    'Orange',
    'Grapefruit',
    'Pineapple',
    'Blood Orange',
    'Meyer Lemon',
    'Tangerine',
    'Yuzu',
    'Key Lime',
  ],
  Bitters: [
    'Angostura Bitters',
    'Orange Bitters',
    'Grapefruit Bitters',
    'Cardamom Bitters',
    'Chocolate Bitters',
    'Cherry Bitters',
    'Celery Bitters',
    'Mole Bitters',
    "Peychaud's Bitters",
    'Black Walnut Bitters',
  ],
  Garnishes: [
    'Lemon Twist',
    'Lime Wedge',
    'Orange Slice',
    'Grapefruit Twist',
    'Pineapple Wedge',
    'Cherry',
    'Olives',
    'Mint Sprig',
    'Basil Leaf',
    'Cucumber Slice',
    'Celery Stalk',
    'Cinnamon Stick',
    'Nutmeg',
    'Coconut Flakes',
    'Maraschino Cherry',
    'Jalapeno Slice',
    'Pickled Onion',
  ],
  Other: [
    'Ice',
    'Water',
    'Soda Water',
    'Sparkling Water',
    'Tonic Syrup',
    'Egg White',
    'Egg Yolk',
    'Heavy Cream',
    'Half-and-Half',
    'Whole Milk',
    'Coconut Milk',
    'Almond Milk',
    'Oat Milk',
  ],
};

export default ingredientsList;
