/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {},
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        smartSipDark: {
          primary: '#2B2D42',
          'primary-content': '#FFFFFF',
          secondary: '#EF233C',
          'secondary-content': '#FFFFFF',
          accent: '#FF9F1C',
          'accent-content': '#000000',
          neutral: '#333333',
          'neutral-content': '#F8F8FF',
          'base-100': '#0D0D0D',
          'base-200': '#1A1A1A',
          'base-300': '#262626',
          'base-content': '#F8F8FF',
          info: '#00ADEF',
          'info-content': '#FFFFFF',
          success: '#4CAF50',
          'success-content': '#FFFFFF',
          warning: '#FFC107',
          'warning-content': '#000000',
          error: '#FF5252',
          'error-content': '#FFFFFF',
        },
        smartSipLight: {
          primary: '#FFFFFF',
          'primary-content': '#262626',
          secondary: '#EF233C',
          'secondary-content': '#FFFFFF',
          accent: '#FF9F1C',
          'accent-content': '#000000',
          neutral: '#D3D3D3',
          'neutral-content': '#262626',
          'base-100': '#FFFDD0',
          'base-200': '#EFE8B0',
          'base-300': '#DFD292',
          'base-content': '#262626',
          info: '#00ADEF',
          'info-content': '#FFFFFF',
          success: '#4CAF50',
          'success-content': '#FFFFFF',
          warning: '#FFC107',
          'warning-content': '#000000',
          error: '#FF5252',
          'error-content': '#FFFFFF',
        },
      },
    ],
  },
};
